USE datn;

CREATE TABLE IF NOT EXISTS EQUIPMENT_TYPE (
  ID bigint NOT NULL AUTO_INCREMENT,
  EQUIPMENT_TYPE_Name varchar(255) NOT NULL,
  EQUIPMENT_TYPE_Description varchar(500),
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EQUIPMENT_MODEL (
  ID bigint NOT NULL AUTO_INCREMENT,
  EQUIPMENT_MODEL_Name varchar(255) NOT NULL,
  EQUIPMENT_MODEL_Branch varchar(255),
  EQUIPMENT_TYPE_ID bigint NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (EQUIPMENT_TYPE_ID) REFERENCES EQUIPMENT_TYPE(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EQUIPMENT_ITEM (
  ID bigint NOT NULL AUTO_INCREMENT,
  EQUIPMENT_ITEM_Name varchar(255) NOT NULL,
  EQUIPMENT_ITEM_PurchaseDate datetime,
  EQUIPMENT_ITEM_Price varchar(255),
  EQUIPMENT_ITEM_Quantity int DEFAULT 1,
  EQUIPMENT_ITEM_Status varchar(255) DEFAULT 'Có sẵn',
  EQUIPMENT_ITEM_Description varchar(500),
  EQUIPMENT_MODEL_ID bigint NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (EQUIPMENT_MODEL_ID) REFERENCES EQUIPMENT_MODEL(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ROOM_TYPE (
  ID bigint NOT NULL AUTO_INCREMENT,
  ROOM_TYPE_Name varchar(255) NOT NULL,
  ROOM_TYPE_Description varchar(500),
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ROOM (
  ID bigint NOT NULL AUTO_INCREMENT,
  ROOM_Name varchar(255) NOT NULL,
  ROOM_Capacity int,
  ROOM_Description varchar(500),
  ROOM_Status varchar(255) DEFAULT 'Có sẵn',
  LOCATION_Building varchar(255),
  LOCATION_Floor varchar(255),
  ROOM_TYPE_ID bigint NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ROOM_TYPE_ID) REFERENCES ROOM_TYPE(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS BORROW_RETURN_SLIP (
  ID bigint NOT NULL AUTO_INCREMENT,
  BORROW_RETURN_SLIP_Name varchar(255),
  BORROW_RETURN_SLIP_Notes varchar(500),
  BORROW_RETURN_SLIP_Status varchar(255) DEFAULT 'Chưa trả',
  USER_ID bigint NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID) REFERENCES USER(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS BORROW_RETURN_DATE (
  ID bigint NOT NULL AUTO_INCREMENT,
  DATE_BorrowDate datetime,
  DATE_ExceptionReturnDate datetime,
  DATE_ActualReturnDate datetime,
  BORROW_RETURN_SLIP_ID bigint NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (BORROW_RETURN_SLIP_ID) REFERENCES BORROW_RETURN_SLIP(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS BORROW_RETURN_ITEM (
  ID bigint NOT NULL AUTO_INCREMENT,
  EQUIPMENT_ITEM_ID bigint,
  ROOM_ID bigint,
  BORROW_RETURN_SLIP_ID bigint NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (BORROW_RETURN_SLIP_ID) REFERENCES BORROW_RETURN_SLIP(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS REQUEST_SLIP (
  ID bigint NOT NULL AUTO_INCREMENT,
  REQUEST_SLIP_Name varchar(255),
  REQUEST_SLIP_RequestDate datetime,
  REQUEST_SLIP_Status varchar(255) DEFAULT 'Chưa duyệt',
  REQUEST_SLIP_Description varchar(500),
  REQUEST_SLIP_ApproveNotes varchar(500),
  REQUESTER_ID bigint,
  APPROVER_ID bigint,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS REQUEST_ITEM (
  ID bigint NOT NULL AUTO_INCREMENT,
  REQUEST_SLIP_ID bigint NOT NULL,
  EQUIPMENT_ITEM_Name varchar(255),
  EQUIPMENT_ITEM_Description varchar(500),
  EQUIPMENT_TYPE_Name varchar(255),
  EQUIPMENT_ITEM_Status varchar(255),
  REQUEST_ITEM_Status varchar(255),
  EQUIPMENT_ITEM_ID bigint,
  PRIMARY KEY (ID),
  FOREIGN KEY (REQUEST_SLIP_ID) REFERENCES REQUEST_SLIP(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Sample equipment data
INSERT IGNORE INTO EQUIPMENT_TYPE (ID, EQUIPMENT_TYPE_Name, EQUIPMENT_TYPE_Description) VALUES
(1, 'Thiết bị điện tử', 'Máy tính, máy chiếu, màn hình'),
(2, 'Dụng cụ thí nghiệm', 'Dụng cụ phòng lab');

INSERT IGNORE INTO EQUIPMENT_MODEL (ID, EQUIPMENT_MODEL_Name, EQUIPMENT_MODEL_Branch, EQUIPMENT_TYPE_ID) VALUES
(1, 'Máy chiếu Epson', 'Epson', 1),
(2, 'Laptop Dell', 'Dell', 1);

INSERT IGNORE INTO EQUIPMENT_ITEM (ID, EQUIPMENT_ITEM_Name, EQUIPMENT_ITEM_PurchaseDate, EQUIPMENT_ITEM_Price, EQUIPMENT_ITEM_Quantity, EQUIPMENT_ITEM_Status, EQUIPMENT_ITEM_Description, EQUIPMENT_MODEL_ID) VALUES
(1, 'Máy chiếu phòng A1', '2023-01-01', '15000000', 1, 'Có sẵn', 'Máy chiếu phòng học A1', 1),
(2, 'Laptop giáo viên 01', '2023-06-01', '20000000', 1, 'Có sẵn', 'Laptop dành cho giáo viên', 2);

INSERT IGNORE INTO ROOM_TYPE (ID, ROOM_TYPE_Name, ROOM_TYPE_Description) VALUES
(1, 'Phòng học', 'Phòng học thông thường'),
(2, 'Phòng thí nghiệm', 'Phòng thực hành thí nghiệm');

INSERT IGNORE INTO ROOM (ID, ROOM_Name, ROOM_Capacity, ROOM_Description, ROOM_Status, LOCATION_Building, LOCATION_Floor, ROOM_TYPE_ID) VALUES
(1, 'Phòng A101', 40, 'Phòng học tầng 1 nhà A', 'Có sẵn', 'Nhà A', 'Tầng 1', 1),
(2, 'Phòng Lab 01', 30, 'Phòng thí nghiệm vật lý', 'Có sẵn', 'Nhà B', 'Tầng 2', 2);
